### ISSUE TITLE
O Script docker-interfaces.sh esta executando muito lento

### ISSUE THREAD

**Issue by adonaicanez** [adonaicanez/docker-monitor#3]
O script docker-interfaces.sh executa muito lento e por isso o zabbix server não consegue identificar as interfaces dos containers em execução.

Precisa fazer ele retornar os dados solicitados mais rapidamente, para evitar esse problema. Abaixo tem o tempo de execução de um teste.

root@client:/opt/docker-monitor# time ./docker-interfaces.sh
{
        "data":[

        {"{#CONTAINERNAME}":"elegant_rosalind",                         "{#CONTAINERINTERFACE}":"eth0"},
        {"{#CONTAINERNAME}":"optimistic_edison",                                "{#CONTAINERINTERFACE}":"eth0"}

        ]
}

real    0m3.046s
user    0m0.049s
sys     0m0.008s

**Comment by vnirocha** [comment]
A lentidão se dava pelo fato de que o script de auto-discovery estava fazendo consultas desnecessárias a API. Com o novo update, o script irá consultar arquivos que estão na memória. 

Resultado obtido após as alterações mencionadas:
real	0m0.053s
user	0m0.036s
sys	0m0.013s
